AspNetCoreBank/Controllers/ClientController.cs
using System.Threading.Tasks;
using AspNetCoreBank.Models;
using AspNetCoreBank.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreBank.Controllers
{
  public class ClientController : Controller
  {
      private readonly IClientService _ClientService;

      public ClientController(IClientService ClientService) => _ClientService = ClientService;
        
        [Authorize]
        public async Task<IActionResult> Index(int Document)
        {
          
            // Get clients from database
            var client = await _ClientService.GetClient(Document);
            // Put clients into a model
            var model = new ClientsViewModel
            {
                Clients = (client != null) ? new Client[] { client } : null
            };
            // Render view using the model
            return View(model);
        }
  }
}

AspNetCoreBank/Controllers/ManageUsersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using AspNetCoreBank.Models;
using Microsoft.EntityFrameworkCore;
namespace AspNetCoreBank.Controllers
{
    [Authorize(Roles = AspNetCoreBank.Data.Constants.AdministratorRole)]
    public class ManageUsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        public ManageUsersController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }
        
        public async Task<IActionResult> Index()
        {
            var admins = (await _userManager.GetUsersInRoleAsync(AspNetCoreBank.Data.Constants.AdministratorRole)).ToArray();
            var everyone = await _userManager.Users.ToArrayAsync();
            var model = new ManageUsersViewModel
            {
                Administrators = admins,
                Everyone = everyone
            };
            return View(model);
        }
}
}

AspNetCoreBank/Controllers/ProductsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreBank.Models;
using AspNetCoreBank.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreBank.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductsService _ProductsService;
        private readonly IProductTypeService _productTypeService;
        public ProductsController(IProductsService ProductsService, IProductTypeService productTypeService)
        {
            _ProductsService = ProductsService;
            _productTypeService = productTypeService;
        }
        
        [Authorize]
        public async Task<IActionResult> Index(int ClientId, int Id)
        {
            if (ClientId == 0)
                return Redirect("Client");
            // Get Products from database
            var Products = await _ProductsService.GetProductsByClientId(ClientId);
            if (Id == 0)
                Id = Products.ToList().FirstOrDefault().Id;
            var productDetail = await _ProductsService.GetProductDetailById(Id);
            var productMovements = await _ProductsService.GetByProductId(Id);
            var productTypes = await _productTypeService.GetAll();
            

            // Put Products into a model
            var model = new ProductsViewModel()
            {
                Products = Products,
                ProductDetail = productDetail,
                ProductMovements = productMovements,
                ProductTypes = productTypes
            };
            // Render view using the model
            return View(model);
        }
  }
  
}

AspNetCoreBank/Views/Shared/_AdminActionsPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using AspNetCoreBank.Data
@inject SignInManager<IdentityUser> signInManager
@inject UserManager<IdentityUser> userManager
@if (signInManager.IsSignedIn(User))
{
    var currentUser = await userManager.GetUserAsync(User);
    var isAdmin = currentUser != null
    && await userManager.IsInRoleAsync(
        currentUser,
        Constants.AdministratorRole);
    if (isAdmin)
    {
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a asp-controller="ManageUsers" asp-action="Index">Manage Users</a>
            </li>
        </ul>
    }
}

AspNetCoreBank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreBank</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Client" asp-action="Index">Gestión de Cliente</a></li>
                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Gestión de Productos</a></li>
                </ul>
				<partial name="_LoginPartial" />
				<partial name="_AdminActionsPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container" style="padding-top: 5%;">@RenderBody()</div>

    <div class="container footer body-content">
        <hr />
        <footer>
            <p>&copy; 2019 - AspNetCoreBank</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>